** Variables **

${EMAIL_INPUT_SELECTOR}             //input[@name="login"]
${SENHA_INPUT_SELECTOR}             //input[@name="password"]
${EMAIL_2_INPUT_SELECTOR}           //input[@autocomplete="username"]
${BUTTON_SELECTOR}                  css:button.LoginBox-form-continue
${BUTTON_2_SELECTOR}                //button[@id="login-box-form-continue"]
${BUTTON_USER}                      //button[@data-testid="dropdown-title"]

